screens:
  xs: 440px
  sm: 640px
  md: 768px
  lg: 1024px
  xl: 1280px
  2xl: 1536px
colors:
  transparent: transparent
  current: currentColor
  black: "#000"
  white: "#fff"
  slate: "#64748b"
  gray: "#6b7280"
  zink: "#71717a"
  neutral: "#737373"
  stone: "#78716c"
  red: "#ef4444"
  orange: "#f97316"
  amber: "#f59e0b"
  yellow: "#eab308"
  lime: "#84cc16"
  green: "#22c55e"
  emerald: "#10b981"
  teal: "#14b8a6"
  cyan: "#06b6d4"
  sky: "#0ea5e9"
  blue: "#3b82f6"
  indigo: "#6366f1"
  violet: "#8b5cf6"
  purple: "#a855f7"
  fuchsia: "#d946ef"
  pink: "#ec4899"
  rose: "#f43f5e"
animation:
  spin: spin var(--tw-animation-duration) linear infinite
  ping: ping var(--tw-animation-duration) cubic-bezier(0, 0, 0.2, 1) infinite
  pulse: pulse var(--tw-animation-duration) cubic-bezier(0.4, 0, 0.6, 1) infinite
  bounce: bounce var(--tw-animation-duration) infinite
  shake: shake var(--tw-animation-duration) cubic-bezier(.36,.07,.19,.97)
  scroll: scroll var(--tw-animation-duration) linear infinite
keyframes:
  spin:
    from:
      transform: rotate(0deg)
    to:
      transform: rotate(360deg)
  ping:
    75%, 100%:
      transform: scale(2)
      opacity: 0
  pulse:
    0%,100%:
      opacity: 1
    50%:
      opacity: .5
  bounce:
    0%, 100%:
      transform: translateY(-25%)
      animationTimingFunction: cubic-bezier(0.8, 0, 1, 1)
    50%:
      transform: translateY(0)
      animationTimingFunction: cubic-bezier(0, 0, 0.2, 1)
  shake:
    10%,90%:
      transform: translate3d(-1px, 0, 0);
    20%,80%:
      transform: translate3d(2px, 0, 0);
    30%,50%,70%:
      transform: translate3d(-4px, 0, 0);
    40%,60%:
      transform: translate3d(4px, 0, 0);
  scroll:
    0%:
      transform: translateX(0%);
    100%:
      transform: translateX(-50%);
borderColor:
  DEFAULT: rgba(0,0,0,0.08)
borderRadius:
  full: 9999px
borderWidth:
  DEFAULT: 1px
divideWidth:
  DEFAULT: 1px
dropShadow:
  sm: 0 1px 1px rgba(0,0,0,0.05)
  DEFAULT:
    - 0 1px 2px rgba(0, 0, 0, 0.1)
    - 0 1px 1px rgba(0, 0, 0, 0.06)
  md:
    - 0 4px 3px rgba(0, 0, 0, 0.07)
    - 0 2px 2px rgba(0, 0, 0, 0.06)
  lg:
    - 0 10px 8px rgba(0, 0, 0, 0.04)
    - 0 4px 3px rgba(0, 0, 0, 0.1)
  xl:
    - 0 20px 13px rgba(0, 0, 0, 0.03)
    - 0 8px 5px rgba(0, 0, 0, 0.08)
  2xl: 0 25px 25px rgba(0, 0, 0, 0.15)
  none: "0 0 #0000"
flex:
  1: 1 1 0%
  auto: 1 1 auto
  initial: 0 1 auto
  none: none
flexGrow:
  0: 0
  DEFAULT: 1
flexShrink:
  0: 0
  DEFAULT: 1
fontFamily:
  sans:
    - "system-ui"
    - "sans-serif"
  serif:
    - "serif"
  mono:
    - "Menlo"
    - "Monaco"
    - "Consolas"
    - '"Liberation Mono"'
    - '"Courier New"'
    - "monospace"
fontWeight:
  hairline: 100
  thin: 200
  light: 300
  normal: 400
  medium: 500
  semibold: 600
  bold: 700
  extrabold: 800
  black: 900
inset:
  0: 0px
letterSpacing:
  tighter: -0.05em
  tight: -0.025em
  normal: 0
  wide: 0.025em
  wider: 0.05em
  widest: 0.1em
lineHeight:
  none: 1
  tight: 1.25
  snug: 1.375
  normal: 1.5
  relaxed: 1.625
  loose: 2
objectPosition:
  bottom: bottom
  center: center
  left: left
  left-bottom: left bottom
  left-top: left top
  right: right
  right-bottom: right bottom
  right-top: right top
  top: top
order:
  first: -9999
  last: 9999
  none: 0
strokeWidth:
  0: 0
  1: 1
  2: 2
textShadow:
  DEFAULT: 0px 1px 1px rgba(0,0,0,0.5)
  sm: 0px 1px 2px rgba(0,0,0,0.5)
  md: 0px 1px 3px rgba(0,0,0,0.5)
  lg: 0px 2px 4px rgba(0,0,0,0.5)
  xl: 0px 2px 5px rgba(0,0,0,0.5)
translate:
  full: 100%'
transitionProperty:
  none: none
  all: all
  DEFAULT: background-color,border-color,color,fill,stroke,opacity,box-shadow,transform
  colors: background-color,border-color,color,fill,stroke
  opacity: opacity
  shadow: box-shadow
  transform: transform
transitionTimingFunction:
  linear: linear
  in: cubic-bezier(0.4,0,1,1)
  out: cubic-bezier(0,0,0.2,1)
  in-out: cubic-bezier(0.4,0,0.2,1)
transformOrigin:
  center: center
  top: top
  top-right: top right
  right: right
  bottom-right: bottom right
  bottom: bottom
  bottom-left: bottom left
  left: left
  top-left: top left
